// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0LvJbmRYrAGxVnp5DmZqAqROx5gZ5JU',
    appId: '1:1775172545:web:a58bb3987ee09a618ecd40',
    messagingSenderId: '1775172545',
    projectId: 'afronex-e762b',
    authDomain: 'afronex-e762b.firebaseapp.com',
    storageBucket: 'afronex-e762b.appspot.com',
    measurementId: 'G-W9BE7Z4H54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsHhvH463OOMQuNi70_vIT2X6NVHlCsmQ',
    appId: '1:1775172545:android:21fad9de505c554d8ecd40',
    messagingSenderId: '1775172545',
    projectId: 'afronex-e762b',
    storageBucket: 'afronex-e762b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6aOfA5XsXz909fbZg3rMfIQ5wQM_5n1s',
    appId: '1:1775172545:ios:36de293b637516678ecd40',
    messagingSenderId: '1775172545',
    projectId: 'afronex-e762b',
    storageBucket: 'afronex-e762b.appspot.com',
    iosBundleId: 'com.example.afronexTask4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6aOfA5XsXz909fbZg3rMfIQ5wQM_5n1s',
    appId: '1:1775172545:ios:22346c17573d95e48ecd40',
    messagingSenderId: '1775172545',
    projectId: 'afronex-e762b',
    storageBucket: 'afronex-e762b.appspot.com',
    iosBundleId: 'com.example.afronexTask4.RunnerTests',
  );
}
